#Dockerize API

FROM node:20-alpine AS base

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /usr/src/app
RUN npm install -g turbo
COPY . .
RUN turbo prune main-api bank-api payment-webhook user-web --docker
COPY .env out/full/.env


# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /usr/src/app/out/json/ .
COPY --from=builder /usr/src/app/out/package-lock.json ./package-lock.json
RUN npm install

COPY --from=builder /usr/src/app/out/full/ .
COPY turbo.json turbo.json

RUN npm run db:generate

FROM base AS runner
WORKDIR /usr/src/app
COPY --from=installer /usr/src/app .

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 5173

CMD ["npm","run","dev"]
