#Dockerize API

FROM node:20-alpine AS base

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /usr/src/app
RUN npm install -g turbo
COPY . .

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /usr/src/app .
RUN npm install

COPY turbo.json turbo.json

RUN npm run db:generate

FROM base AS runner
WORKDIR /usr/src/app

# Don't run production as root
# Doesn't work currently
# RUN addgroup --system --gid 1001 expressjs
# RUN adduser --system --uid 1001 expressjs
# USER expressjs
COPY --from=installer /usr/src/app .

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 5173

CMD ["npm","run","dev"]