#Dockerize API

FROM node:20-alpine AS base

RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /usr/src/app
RUN npm install -g turbo
COPY . .
RUN npm install

RUN npm run db:generate

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 5173

# CMD ["npm","run","dev"]
CMD ["sleep", "infinity"]