#Dockerize APP for dev

FROM node:20-alpine3.18 AS base

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /usr/src/app
RUN npm install -g turbo
COPY . .
RUN turbo prune main-api bank-api payment-webhook websocket user-web --docker


# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /usr/src/app/out/json/ .
COPY --from=builder /usr/src/app/out/package-lock.json ./package-lock.json
RUN npm install

COPY --from=builder /usr/src/app/out/full/ .
COPY turbo.json turbo.json

COPY .env .env

FROM base AS runner
# RUN apk add --no-cache
WORKDIR /usr/src/app
COPY --from=installer /usr/src/app .

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 8080
EXPOSE 5173

CMD npm run db:migrate && sleep 20 && npm run dev