openapi: 3.0.0
info:
  title: Main API, Ramp route
  version: 1.0.0
  description: Ramp endpoints

servers:
  - url: http://localhost:3000/api/v1/ramp
    description: Local ramp server

paths:
  /hdfc/onramp:
    post:
      summary: Inpay deposit from HDFC
      description: Deposit money from HDFC
      parameters:
        - $ref: "#/components/parameters/AuthCookie"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Amount to deposit
                currency:
                  type: string
                  enum:
                    - INR
                    - USD
                    - AED
                  description: Currency
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/responses/OnRampSuccess"
        "400":
          description: Invalid Request
        "401":
          $ref: "#/components/responses/UnAuthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"

  /hdfc/offramp/get-otp:
    get:
      summary: Get OTP to withdraw from Inpay
      description: Get OTP for withdraw
      parameters:
        - name: amount
          in: query
          required: true
          schema:
            type: number
            description: Amount to withdraw
        - $ref: "#/components/parameters/AuthCookie"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - OTP sent
        "400":
          description: Invalid Request
        "401":
          $ref: "#/components/responses/UnAuthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"

  /hdfc/offramp/verify-otp:
    post:
      summary: Verify OTP to withdraw from Inpay
      description: Verify OTP for withdraw
      parameters:
        - $ref: "#/components/parameters/AuthCookie"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: OTP to verify
                amount:
                  type: number
                  description: Amount to withdraw
                currency:
                  type: string
                  enum:
                    - INR
                    - USD
                    - AED
                  description: Currency
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - Withdrawal Successful
        "400":
          description: Invalid Request
        "401":
          $ref: "#/components/responses/UnAuthorizedError"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  parameters:
    AuthCookie:
      name: token
      in: cookie
      description: The token to authenticate the user
      required: true
      schema:
        type: string
        format: token
  responses:
    OnRampSuccess:
      description: Onramp success
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                enum:
                  - Request Successful
              token:
                type: string
                format: token
                description: Token generated by HDFC
    InvalidRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Invalid request
    UnAuthorizedError:
      description: Unauthorized request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                enum:
                  - Unauthorized
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                enum:
                  - Request Failed
