name: Deploy Backend to Azure Container Apps
on:
  push:
    branches:
      - deploy

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      -run: pwd
      -run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.ACR_NAME }}
          containerAppName: ${{ vars.CONTAINER_APP1_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          dockerfilePath: dockerfiles/api-prod/Dockerfile
          buildArguments: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
